Navitas/ViewModels/Building/AddInfoEditModel.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;
using System.Web.Mvc;

using Navitas.Infrastructure.MvcHelpers;

namespace Navitas.ViewModels.Building
{
    using BL = Soft33.EnergyPassport.V2.BL;

    public class AddInfoEditModel
    {
        //[LocalizedDisplayName("BuildingGeneral_Name", NameResourceType = typeof(Resources.Names))]
        //[LocalizedDescription("BuildingGeneral_Name_Description", NameResourceType = typeof(Resources.Names))]
        //public string Name { get; set; }

        //[LocalizedDisplayName("BuildingGeneral_Purpose", NameResourceType = typeof(Resources.Names))]
        //[LocalizedDescription("BuildingGeneral_Purpose_Description", NameResourceType = typeof(Resources.Names))]
        //public string Purpose { get; set; }

        /* Атрибут Required определяется для целочисленных, чтобы переопределить дефолтовое сообщение data-val-required.
        */

        [LocalizedDisplayName("BuildingGeneral_StoreysNumber", NameResourceType = typeof(Resources.Names))]
        [LocalizedDescription("BuildingGeneral_StoreysNumber_Description", NameResourceType = typeof(Resources.Names))]
        [Range(1, 200, ErrorMessageResourceName = "NumberOfFloorExceeded", ErrorMessageResourceType = typeof(Resources.ValidationStrings))]
        [Required(ErrorMessageResourceName = "PropertyValueRequired", ErrorMessageResourceType = typeof(Navitas.Resources.ValidationStrings))]
        public int NumberOfFloor { get; set; }

        [LocalizedDisplayName("BuildingGeneral_EntranceNumber", NameResourceType = typeof(Resources.Names))]
        [LocalizedDescription("BuildingGeneral_EntranceNumber_Description", NameResourceType = typeof(Resources.Names))]
        [Range(1, 20, ErrorMessageResourceName = "NumberOfEntrancesExceeded", ErrorMessageResourceType = typeof(Resources.ValidationStrings))]
        [Required(ErrorMessageResourceName = "PropertyValueRequired", ErrorMessageResourceType = typeof(Navitas.Resources.ValidationStrings))]
        public int NumberOfEntrances { get; set; }

        /// <summary>
        /// Год постройки
        /// </summary>
        [LocalizedDisplayName("BuildingGeneral_BuildingYear", NameResourceType = typeof(Resources.Names))]
        [LocalizedDescription("BuildingGeneral_BuildingYear_Description", NameResourceType = typeof(Resources.Names))]        
        public double? BuildingYear { get; set; }

        [LocalizedDisplayName("BuildingGeneral_PowerSupply", NameResourceType = typeof(Resources.Names))]
        [LocalizedDescription("BuildingGeneral_PowerSupply_Description", NameResourceType = typeof(Resources.Names))]
        public int Electro { get; set; }

        [LocalizedDisplayName("BuildingGeneral_HeatingSupply", NameResourceType = typeof(Resources.Names))]
        [LocalizedDescription("BuildingGeneral_HeatingSupply_Description", NameResourceType = typeof(Resources.Names))]
        public int Heat { get; set; }

        [LocalizedDisplayName("BuildingGeneral_WaterSupply", NameResourceType = typeof(Resources.Names))]
        [LocalizedDescription("BuildingGeneral_WaterSupply_Description", NameResourceType = typeof(Resources.Names))]
        public int Water { get; set; }

        [LocalizedDisplayName("BuildingGeneral_WaterDisposal", NameResourceType = typeof(Resources.Names))]
        [LocalizedDescription("BuildingGeneral_WaterDisposal_Description", NameResourceType = typeof(Resources.Names))]
        public int Sewerage { get; set; }

        [LocalizedDisplayName("BuildingGeneral_GasSupply", NameResourceType = typeof(Resources.Names))]
        [LocalizedDescription("BuildingGeneral_GasSupply_Description", NameResourceType = typeof(Resources.Names))]
        public int Gas { get; set; }

        [LocalizedDisplayName("BuildingGeneral_City", NameResourceType = typeof(Resources.Names))]
        [LocalizedDescription("BuildingGeneral_City_Description", NameResourceType = typeof(Resources.Names))]
        public int City { get; set; }

        public SelectList ResourceTypeList
        {
            get;
            set;
        }

        public SelectList CityList
        {
            get;
            set;
        }


        public AddInfoEditModel()
        {
            //ResourceTypeList = new SelectList(
            //    new[] { 
            //        new SelectListItem() { Value="0", Text="" },
            //        new SelectListItem() { Value="1", Text="ва" },
            //        new SelectListItem() { Value="2", Text="ываы" },
            //        new SelectListItem() { Value="3", Text="ываыв" }
            //    }, "Value", "Text");
        }

        public AddInfoEditModel(BL.BuildingAdditionalInformation entity)
        {
            ConvertEntity(entity);
        }

        /// <summary>
        /// Загружает данные в объект бизнес-логики
        /// </summary>
        /// <param name="entity"></param>
        public void UpdateEntity(BL.BuildingAdditionalInformation entity)
        {
            entity.NumberOfFloor = NumberOfFloor;
            entity.NumberOfEntrances = NumberOfEntrances;
            entity.BuildingYear = BuildingYear;

            entity.Resources.ElectricityResource = (Electro != 0) ? new BL.ResourceSupplyType(Electro, String.Empty) : null;
            entity.Resources.HeatResource = (Heat != 0) ? new BL.ResourceSupplyType(Heat, String.Empty) : null;
            entity.Resources.WaterResource = (Water != 0) ? new BL.ResourceSupplyType(Water, String.Empty) : null;
            entity.Resources.SewerageResource = (Sewerage != 0) ? new BL.ResourceSupplyType(Sewerage, String.Empty) : null;
            entity.Resources.GasResource = (Gas != 0) ? new BL.ResourceSupplyType(Gas, String.Empty) : null;

            entity.CityCoeffs = (City != 0) ? new BL.CityCoeffs(City, String.Empty) : null;
        }

        /// <summary>
        /// Загружает данные в модель из объекта бизнес-логики
        /// </summary>
        /// <param name="entity"></param>
        private void ConvertEntity(BL.BuildingAdditionalInformation entity)
        {
            NumberOfFloor = entity.NumberOfFloor;
            NumberOfEntrances = entity.NumberOfEntrances;
            BuildingYear = entity.BuildingYear;

            Electro = entity.Resources.ElectricityResource != null ? 
                entity.Resources.ElectricityResource.ResourceSupplyTypeID
                : 0;
            Heat = entity.Resources.HeatResource != null ? 
                entity.Resources.HeatResource.ResourceSupplyTypeID
                : 0;
            Water = entity.Resources.WaterResource != null ? 
                entity.Resources.WaterResource.ResourceSupplyTypeID
                : 0;
            Sewerage = entity.Resources.SewerageResource != null ? 
                entity.Resources.SewerageResource.ResourceSupplyTypeID
                : 0;
            Gas = entity.Resources.GasResource != null ?
                entity.Resources.GasResource.ResourceSupplyTypeID
                : 0;

            City = entity.CityCoeffs != null ? entity.CityCoeffs.CityCoeffsId : 0;
        }

        // Список типов не загружен, когда выполняется POST запрос.
        //private string GetResourceNameById(int id)
        //{
        //    if (ResourceTypeList != null)
        //    {
        //        SelectListItem item = ResourceTypeList.First(i => i.Value == id.ToString());
        //        if (item != null)
        //        {
        //            return item.Text;
        //        }
        //    }
        //    return String.Empty;
        //}
    }
}

Navitas/Controllers/ReportController.cs
using System;
using System.Collections.Generic;
using System.Data.Linq;
using System.Linq;
using System.Web;
using System.Web.Mvc;

using Navitas.Controllers.Structures;
using Navitas.Infrastructure;
using Navitas.Infrastructure.MvcHelpers;
using Navitas.Report;
using Navitas.Services;
using Navitas.ViewModels.Report;

namespace Navitas.Controllers
{
    using BL = Soft33.EnergyPassport.V2.BL;
    using BLExt = Soft33.EnergyPassport.V2.BL.Extended;

    [OutputCache(NoStore = true, Duration = 0, VaryByParam = "*")]
    [HandleError(ExceptionType = typeof(System.Exception), View = "Error", Order = 1)]
    [HandleError(ExceptionType = typeof(Services.Exceptions.ServiceBaseException), View = "Error", Order = 2)]
    [HandleError(ExceptionType = typeof(Services.Exceptions.ConcurrencyException), View = "ConcurrencyError", Order = 10)]
    public class ReportController : ControllerBase
    {
        /// <summary>
        /// Идентификатор шаблона, из которого генерируются другие шаблоны.
        /// </summary>
        private const int MASTER_REPORT_ID = 1;

        private Models.DataManager _dataManager;
        private ServiceManager _services;

        private BL.CalculationThermoCoeffs CalculationThermoCoeffs
        {
            get
            {
                return _services.SettingsService.GetCalculationThermoCoeffs();
            }
        }

        private BL.CalculationFinanceCoeffs CalculationFinanceCoeffs
        {
            get
            {
                return _services.SettingsService.GetCalculationFinanceCoeffs();
            }
        }

        public ReportController(Models.DataManager dataManager, ServiceManager services)
            : base(services)
        {
            _dataManager = dataManager;
            _services = services;

            
        }

        public ActionResult Test(int id)
        {
            BL.Inspection inspection = _services.InspectionService.GetFullInspectionById(id);

            BLExt.InspectionExtended model = _services.InspectionService.CreateInspectionExtended(inspection, CalculationThermoCoeffs, CalculationFinanceCoeffs);

            XslTransformHelper xslTransformer = new XslTransformHelper(Environment.AppSettings.ReportXsltFileFullName);
            RazorHelper razorHelper = new RazorHelper();

            model.Buildings[0].CSEC.SpecificEnergyConsumptionTable.Rows[0].Cells[0] = "<script>alert('hi');</script>";

            string template = ""
                + ""
    + "@{"
        + "{"
            + "Soft33.EnergyPassport.V2.BL.TemplateCalculations.TemplateTable table = Model.Buildings[0].CSEC.SpecificEnergyConsumptionTable;"
        + "<table>"
            
            + "@for(int i = 0; i < table.Rows.Count; i++) {"

               + "<tr class=\"@RowTypeClass(table.Rows[i].RowType)\">"
                + "@if(i == 0) {"
                    + "<td>@table.Rows[i].Cells[0]</td>"
                    + "<td>@table.Rows[i].Cells[1]</td>"
                    + "<td>@table.Rows[i].Cells[2]</td>"
                    + "<td>@table.Rows[i].Cells[3]</td>"

                + "}"
                + "else {"
                    + "<td>@table.Rows[i].Cells[0]</td>"
                    + "<td>@FormatDouble2(table.Rows[i].Cells[1])</td>"
                    + "<td>@FormatDouble2(table.Rows[i].Cells[2])</td>"
                    + "<td>@FormatDouble2(table.Rows[i].Cells[3])</td>"
                + "}"
                + "</tr>"
            + "} "
        + "</table>"
        + "}"
     + "}"
                + ""
                + "";

            ViewBag.HtmlLayout = razorHelper.Parse<BLExt.InspectionExtended>(template, model);

            return View(model);
        }

        [HttpGet]
        [Authorize()]
        public ActionResult Edit(int id)
        {
            // Необходимо, чтобы объект Inspection также содержал Buildings, т.к. по ним будет строится отчет в случае генерации
            BL.Inspection inspection = _services.InspectionService.GetFullInspectionById(id);
            if (inspection != null)
            {
                BLExt.InspectionExtended extInspection = _services.InspectionService.CreateInspectionExtended(inspection, CalculationThermoCoeffs, CalculationFinanceCoeffs);

                // 1. Проверить существует ли отчет. Если еще не создан, то сгенерировать
                InspectionReport report = _services.ReportService.CreateOrGetExistingReport(MASTER_REPORT_ID, inspection);//id);

                // ... Подготовить данные отчета
                _services.ReportService.PrerenderInspection(extInspection, Environment);

                if (report == null)
                {
                    throw new InvalidOperationException("Ошибка при копировании мастер-шаблона.");
                }

                // 2. Загрузка отчета в форму
                XslTransformHelper xslTransformer = new XslTransformHelper(Environment.AppSettings.ReportXsltFileFullName);
                RazorHelper razorHelper = new RazorHelper();

                ViewModels.Report.ReportEditModel model = new ViewModels.Report.ReportEditModel(xslTransformer, razorHelper, report, extInspection);
                model.InspectionId = id;

                // В получившейся разметке необходимо декодироваться всякие &lt; &gt; получившиеся после xml-сериализации.
                // Сделать это можно либо в XLST либо здесь.
                //model.HtmlLayout = Server.HtmlDecode(model.HtmlLayout);

                return View(model);
            }
            else
            {
                return NotFound();
            }
        }

        [HttpPost]
        [Authorize()]
        public ActionResult Edit(int id, string regenerate, FormCollection form)
        {
            // Проверить, чтобы регенерация отчета была только когдаль пользователь нажал на кнопку,
            // иначе просто вернуть отчет.
            if (String.IsNullOrEmpty(regenerate))
            {
                return Edit(id);
            }

            // Необходимо, чтобы объект Inspection также содержал Buildings, т.к. по ним будет строится отчет
            BL.Inspection inspection = _services.InspectionService.GetFullInspectionById(id);
            if (inspection != null)
            {
                BLExt.InspectionExtended extInspection = _services.InspectionService.CreateInspectionExtended(inspection, CalculationThermoCoeffs, CalculationFinanceCoeffs);

                // ... Подготовить данные отчета
                _services.ReportService.PrerenderInspection(extInspection, Environment);

                InspectionReport report = _services.ReportService.RegenerateReport(MASTER_REPORT_ID, inspection);//id);

                if (report == null)
                {
                    throw new InvalidOperationException("Ошибка при копировании мастер-шаблона.");
                }

                // 2. Загрузка отчета в форму
                XslTransformHelper xslTransformer = new XslTransformHelper(Environment.AppSettings.ReportXsltFileFullName);
                RazorHelper razorHelper = new RazorHelper();

                ViewModels.Report.ReportEditModel model = new ViewModels.Report.ReportEditModel(xslTransformer, razorHelper, report, extInspection);
                model.InspectionId = id;

                return View(model);
            }
            else
            {
                return NotFound();
            }
        }


        //[HttpPost]
        //public ActionResult HideText(FormCollection form)
        //{
        //    return HandleAjaxExceptions(delegate()
        //    {
        //        // Загрузить параметры из запроса
        //        int sectionId = SectionEditModel.ParseTextId(form["sectionId"]);
        //        int paragraphId = EditableTextElementEditModel.ParseTextId(form["paragraphId"]);
        //        Binary timestamp = ConvertHelper.ParseBinary(form["timestamp"]);

        //        // Спрятать текстовый параграф раздела.
        //        Binary newTimestamp = _services.ReportService.HideEditableTextElement(sectionId, paragraphId, timestamp);

        //        JsonStructureResult result = new JsonStructureResult();
        //        result.result = new { sectionTimestamp = ConvertHelper.Convert(newTimestamp) };
        //        return result;
        //    });
        //}

        ///// <summary>
        ///// Скрывает блок, в котором отображаются обязательные картинки для разделов (напр., "общий вид здания" и т.п.)
        ///// </summary>
        ///// <param name="form"></param>
        ///// <returns></returns>
        //[HttpPost]
        //public ActionResult HideRequiredImageBlock(FormCollection form)
        //{
        //    return HandleAjaxExceptions(delegate()
        //    {
        //        // Загрузить параметры из запроса
        //        int sectionId = SectionEditModel.ParseTextId(form["sectionId"]);
        //        int blockId = RequiredImageElementEditModel.ParseTextId(form["blockId"]);
        //        Binary timestamp = ConvertHelper.ParseBinary(form["timestamp"]);

        //        // Спрятать иллюстрацию
        //        Binary newTimestamp = _services.ReportService.HideRequiredImageElement(sectionId, blockId, timestamp);

        //        JsonStructureResult result = new JsonStructureResult();
        //        result.result = new { sectionTimestamp = ConvertHelper.Convert(newTimestamp) };
        //        return result;
        //    });
        //}

        [HttpPost]
        public ActionResult HideElement(FormCollection form)
        {
            return HandleAjaxExceptions(delegate()
            {
                // Загрузить параметры из запроса
                int sectionId = SectionEditModel.ParseTextId(form["sectionId"]);
                int elementId = BaseElementEditModel.ParseTextId(form["elementId"]);
                Binary timestamp = ConvertHelper.ParseBinary(form["timestamp"]);

                // Спрятать иллюстрацию

Navitas/Views/Inspection/Buildings.cshtml
@model Navitas.ViewModels.Building.BuildingListEditModel
           
@{
    Layout = "~/Views/Inspection/_Layout.cshtml";
    ViewBag.Title = @Navitas.Resources.Strings.InspectionBuildingsTitle;
}

<script type="text/javascript">

    // Функция, описывающая объект для формы Транспорта
    function InspectionBuildingsViewType() {

        var self = this; // Для обработчиков событий
        this.containerId = "building-container";
        this.formId = "formBuildings";
        this.rowSelector = ".buildingRow";
        this.numberContainerSelector = ".orderNumber";
        this.urlNewUnit = "/Inspection/GetNewBuildingItem";
        this.addButtonId = "btnAddItem";
        this.removeButtonSelector = ".removeItem";

        // Обработчик события нажатия на кнопку добавления нового элемента
        this.addItem_onClick = function () {
            self.addItem();
            return false;
        }

        this.removeItem_onClick = function () {
            self.removeItem(this); // передаем button input в качестве параметра
            return false;
        }
    }

    // Унаследоваться от базового представления
    extend(InspectionBuildingsViewType, Navitas.DynamicListView);

    // Переопределить функции

    InspectionBuildingsViewType.prototype.base_onLoad = Navitas.DynamicListView.prototype.onLoad;
    InspectionBuildingsViewType.prototype.onLoad = function () {
        this.base_onLoad();

    };

    InspectionBuildingsViewType.prototype.base_onUnload = Navitas.DynamicListView.prototype.onUnload;
    InspectionBuildingsViewType.prototype.onUnload = function () {
    };

    // Инициализует элементы формы при загрузке
    InspectionBuildingsViewType.prototype.base_initControls = Navitas.DynamicListView.prototype.initControls;
    InspectionBuildingsViewType.prototype.initControls = function (container) {

        this.base_initControls(container);

        if (typeof (container) == 'undefined' || container == null) {
            $("#" + this.addButtonId).click(this.addItem_onClick);
        }

        if (typeof (container) !== 'undefined' && container != null) {
            $(this.removeButtonSelector, container).click(this.removeItem_onClick);
        }
        else {
            $(this.removeButtonSelector, "#" + this.containerId).click(this.removeItem_onClick);
        }
    };

    // Фукнция вызываемая перед отправкой запроса на добавление элемента
    InspectionBuildingsViewType.prototype.base_beforeRequestAddItem = Navitas.DynamicListView.prototype.beforeRequestAddItem;
    InspectionBuildingsViewType.prototype.beforeRequestAddItem = function () {
        this.base_beforeRequestAddItem();
        $("#" + this.addButtonId).attr('disabled', 'disabled');
    };

    // Функция, вызываемы после выполнения запроса на добавление элемента
    InspectionBuildingsViewType.prototype.base_afterRequestAddItem = Navitas.DynamicListView.prototype.afterRequestAddItem;
    InspectionBuildingsViewType.prototype.afterRequestAddItem = function () {
        this.base_afterRequestAddItem();
        $("#" + this.addButtonId).removeAttr('disabled');
    };


    var InspectionBuildingsView = new InspectionBuildingsViewType();


</script>


<script type="text/javascript">
    $(document).ready(function () {
        InspectionBuildingsView.onLoad();
    });


    $(window).unload(function () {
        InspectionBuildingsView.onUnload();
    });   

</script>

@using (Html.BeginForm("Buildings", "Inspection", FormMethod.Post, new { id = "formBuildings" }))
{
    <p>
        @Html.Partial("_Navigation")
    </p>
    
    <h2>@Navitas.Resources.Strings.InspectionBuildingsFieldset</h2>
    
    @Html.ValidationSummary(false, @Navitas.Resources.ValidationStrings.SomeFieldIsNotValid, new { id = "buildings-validation" })

    <table id="building-container" class="singlerows">
        @for (int i = 0; i < Model.Items.Count; i++)
        {
            @Html.EditorFor(model => model.Items[i], "_BuildingItem", new { index = i, BulidingPurposeList = Model.BuildingPurposeList })
        }
    </table>

    <p></p>
    <p>
        <input id="btnAddItem" type="submit" name="addItem" value="@Navitas.Resources.Strings.AddItem" title="@Navitas.Resources.Strings.AddItemDescription" />
    </p>
    
    <p>
        @{ Html.RenderPartial("_ViewNavigation", Navitas.Controls.ViewNavigationItems.Prev | Navitas.Controls.ViewNavigationItems.Save); }
    </p>    
}

Navitas/Views/Inspection/CalculationCoeffs.cshtml
@model Navitas.ViewModels.Inspection.CalculationCoeffsEditModel
           
@{
    ViewBag.Title = Navitas.Resources.Strings.InspectionCalculationCoeffs_Title;
}

<script type="text/javascript">

    function TechnicalViewType() {
        var self = this;

        this.formId = "formCalculationCoeffs";
    }

    // Унаследоваться от базового представления
    extend(TechnicalViewType, Navitas.ViewBase);

    // Переопределить функции

    TechnicalViewType.prototype.base_onLoad = Navitas.ViewBase.prototype.onLoad;
    TechnicalViewType.prototype.onLoad = function () {
        this.base_onLoad();
        this.initControls("#" + this.formId);
    };

    TechnicalViewType.prototype.base_onUnload = Navitas.ViewBase.prototype.onUnload;
    TechnicalViewType.prototype.onUnload = function () {
    };

    // Инициализует элементы формы при загрузке
    TechnicalViewType.prototype.base_initControls = Navitas.ViewBase.prototype.initControls;
    TechnicalViewType.prototype.initControls = function (container) {
        this.base_initControls(container);
        var self = this;

    };


    var TechnicalView = new TechnicalViewType();

</script>

<script type="text/javascript">
    $(document).ready(function () {

        TechnicalView.onLoad();
    });

    $(window).unload(function () {

        TechnicalView.onUnload();
    });   
</script>

@using (Html.BeginForm("CalculationCoeffs", "Inspection", FormMethod.Post, new { id = "formCalculationCoeffs" }))
{
    <p>
        @Html.Partial("_Navigation")
    </p>
    
    <h2>@Navitas.Resources.Strings.InspectionCalculationCoeffs_Fieldset</h2>
    
    @Html.ValidationSummary(false, @Navitas.Resources.ValidationStrings.SomeFieldIsNotValid, new { id = "calculationcoeffs-validation" })

    <table class="consecutive">

        @* Тариф на тепло *@
        <tr>
            <td><div class="editor-label">@Html.Encode(Navitas.Resources.Names.Technical_ThermoEnergyTariff + ", " + Navitas.Resources.Strings.Technical_ThermoEnergyTariff_Unit)</div></td>
            <td>
                <div class="editor-field">
                    @Html.EditorFor(model => model.ThermoEnergyTariff)
                </div>
                <div class="validationmessage">
                    @Html.ValidationMessageFor(model => model.ThermoEnergyTariff)
                </div>
            </td>
        </tr>

        @* Тариф на холодную воду *@
        <tr>
            <td><div class="editor-label">@Navitas.Resources.Names.Technical_ColdWaterTariff</div></td>
            <td>
                <div class="editor-field">
                    @Html.EditorFor(model => model.ColdWaterTariff)
                </div>
                <div class="validationmessage">
                    @Html.ValidationMessageFor(model => model.ColdWaterTariff)
                </div>
            </td>
        </tr>

        @* Тариф на горячую воду *@
        <tr>
            <td><div class="editor-label">@Navitas.Resources.Names.Technical_HotWaterTariff</div></td>
            <td>
                <div class="editor-field">
                    @Html.EditorFor(model => model.HotWaterTariff)
                </div>
                <div class="validationmessage">
                    @Html.ValidationMessageFor(model => model.HotWaterTariff)
                </div>
            </td>
        </tr>

    </table>
  
    <p></p>
    <p>
        @{ Html.RenderPartial("_ViewNavigation", Navitas.Controls.ViewNavigationItems.Prev | Navitas.Controls.ViewNavigationItems.Save | Navitas.Controls.ViewNavigationItems.Next); }
    </p>    
}

Navitas/Views/Inspection/Details.cshtml
@model Soft33.EnergyPassport.V2.BL.Inspection
@{
    var client = (Soft33.EnergyPassport.V2.BL.Client)ViewData["Client"];
    var inspection = (Soft33.EnergyPassport.V2.BL.Inspection)ViewData["InspectionDetails"];
    ViewBag.Title = "Обследование: " + inspection.FullName;
}

<h2>Обследование: @Html.Raw(inspection.FullName)</h2>

@*<h3>Заказчик</h3>*@

@Html.Partial("_Client", client)

Navitas/Views/Inspection/Index.cshtml
@model Navitas.ViewModels.Inspection.PagedInspectionsModel

@{
    ViewBag.Title = "Список обследований";
}

<h2>Список обследований</h2>

<p>
    @Html.ActionLink(Navitas.Resources.Strings.Action_AddInspection, "Client", "Inspection")
</p>

@{
    var grid = new WebGrid(null, rowsPerPage: Model.PageSize, defaultSort: "ClientCaption");
    grid.Bind(Model.Inspections, rowCount: Model.TotalRows, autoSortAndPage: false);
}

<div class="inspection-list">
    @grid.GetHtml(columns: grid.Columns(
        grid.Column(columnName: "InspectionID", canSort:false, header: "", style: "webgrid-cell",
            format: @<text>@Html.ActionLink("Выбрать", "Client", "Inspection", new { id = item.InspectionID }, new { })</text>),
        grid.Column(columnName: "ClientCaption", header: "Наименование клиента", style: "webgrid-cell"),
        grid.Column(columnName: "Accountant", canSort: false, header: "Ответственный", style: "webgrid-cell"),
        grid.Column(columnName: "AuditorFullName", header: "Аудитор", canSort: false, style: "webgrid-cell"),
        grid.Column(columnName: "State", canSort: false, header: "Статус"),
        grid.Column(columnName: "InspectionID", canSort: false, header: "", style: "webgrid-cell",
            format: @<text>@Html.ActionLink("Отчет", "Edit", "Report", new { id = item.InspectionID }, new { })</text>)
        ),
        tableStyle: "webgrid",
        headerStyle: "webgrid-header",
        footerStyle: "webgrid-footer",
        alternatingRowStyle: "webgrid-alternating-row",
        selectedRowStyle: "webgrid-selected-row",
        rowStyle: "webgrid-row-style"        
    )
</div> 

Navitas/Views/Inspection/_Layout.cshtml
@{
    Layout = "~/Views/Shared/_Layout.cshtml";
}

@RenderBody()