Navitas/Controllers/FileController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

using Navitas.Infrastructure;
using Navitas.Infrastructure.MvcHelpers;
using Navitas.Models;
using Navitas.Services;
using Navitas.Services.Structures;

namespace Navitas.Controllers
{
    public class FileController : ControllerBase
    {
        private DataManager _dataManager;
        private ServiceManager _services;

        public FileController(DataManager dataManager, ServiceManager services)
            : base(services)
        {
            _dataManager = dataManager;
            _services = services;
        }

        //
        // GET: /File/Illustration/2h4h7572h.jpg /File/Illustration/234hhjhg45.txt
        [HttpGet]
        public ActionResult Illustration(string fileName)
        {
            if (!String.IsNullOrEmpty(fileName))
            {
                // 1. Get full path of file
                //File file = _fileRepository.GetByName(fileName);
                FileManager fm = new FileManager(Environment);
                string fileFullPath = fm.GetInspectionIllustrationFullPath(fileName);

                if (!String.IsNullOrEmpty(fileFullPath))
                {
                    // 2. Response to client
                    return File(fileFullPath, FileManager.GetMimeType(fileFullPath), fileName);
                }
            }

            // return 404
            //Response.StatusCode = 404;
            //throw new HttpException(404, "Some description");
            throw new HttpException(404, "Иллюстрация с заданным именем отсутствует.");
        }

        //
        // GET: /File/Thumb/2h4h7572h.jpg
        [HttpGet]
        public ActionResult Thumb(string fileName, int? w, int? h)
        {
            // 1. Search if thumb already exists
            if (!String.IsNullOrEmpty(fileName))
            {
                if (!w.HasValue) w = 100;
                if (!h.HasValue) h = 100;

                ThumbManager tm = new ThumbManager(Environment);
                string thumbFullPath = tm.GetThumb(fileName, w.Value, h.Value);

                // if not exist, create
                if (String.IsNullOrEmpty(thumbFullPath))
                {
                    //File file = _fileRepository.GetByName(fileName);

                    thumbFullPath = tm.CreateThumb(fileName, w.Value, h.Value);
                }

                return File(thumbFullPath, FileManager.GetMimeType(thumbFullPath), fileName);
            }
            // 2. If does not exist create
            throw new HttpException(404, "Иллюстрация с заданным именем отсутствует.");
        }

        [HttpGet]
        public ActionResult Chart(string fileName)
        {
            // 1. Search if thumb already exists
            if (!String.IsNullOrEmpty(fileName))
            {
                ChartManager chm = new ChartManager(Environment);
                string chartFullPath = chm.GetChartFullPath(fileName);

                if (!String.IsNullOrEmpty(chartFullPath))
                {
                    return File(chartFullPath, FileManager.GetMimeType(chartFullPath), fileName);
                }
            }
            // 2. If does not exist create
            throw new HttpException(404, "График с заданным именем отсутствует.");
        }

        [HttpPost]
        public ActionResult AsyncUploadImage(HttpPostedFileBase file, int buildingId, string sectionId, FormCollection form)
        {
            bool errorState = false;    // default error state
            string errorMessage = String.Empty;
            string shortFileName = String.Empty;
            int id = 0;

            string userTitle = form["usertitle"];

            if(String.IsNullOrEmpty(userTitle))
            {
                errorState = true;
                errorMessage = "Не указано название рисунка";
            }
            else if (String.IsNullOrEmpty(sectionId))
            {
                errorState = true;
                errorMessage = "Не указано название раздела";
            }
            else if (file != null && file.ContentLength > 0)
            {
                try
                {
                    int inspectionId = _services.BuildingService.GetInspectionIdByBuildingId(buildingId);

                    if (inspectionId != 0)
                    {
                        // Сохранить файл
                        FileManager fm = new FileManager(Environment);
                        shortFileName = fm.StoreInspectionIllustration(inspectionId, file.InputStream);

                        // Сохранить информацию о файле в базе
                        Models.Illustration illustration = new Illustration();
                        illustration.BuildingID = buildingId;
                        illustration.InspectionID = inspectionId;
                        illustration.FileName = shortFileName;
                        illustration.DivisionName = StringHelper.Substring(sectionId, 512);
                        illustration.UserTitle = StringHelper.Substring(userTitle, 512);
                        id = _dataManager.IllustrationModels.Add<int>(illustration, "IllustrationID");
                    }
                    else
                    {
                        errorState = true;
                        errorMessage = "Обследование не найдено.";
                    }
                }
                catch (Exception ex)
                {
                    errorState = true;
                    errorMessage = ex.Message;
                }
            }

            return new AsyncUploadJsonResult
            {
                Data = new
                {
                    errorMessage = errorMessage,
                    errorState = errorState,
                    fileDescriptor = new { 
                            FileId = id,
                            FileName = shortFileName,
                            UserTitle = userTitle,
                            DivisionName = sectionId,
                            ImageUrl = "/File/Illustration/" + shortFileName,
                            ThumbUrl = "/File/Thumb/" + shortFileName
                        }
                }
            };
        }

        public class IllustrationInfo
        {
            public int IllustrationId {get; set;}
            public string FileName {get; set;}
            public string UserTitle {get; set;}
            public string DivisionName {get; set;}
            public string ImageUrl {get; set;}
            public string ThumbUrl { get; set; }
        }

        [HttpPost]
        public ActionResult AsyncGetImages(FormCollection form)
        {
            bool errorState = false;    // default error state
            string errorMessage = String.Empty;

            List<IllustrationInfo> illustrations = new List<IllustrationInfo>();

            try
            {
                int inspectionId;

                Int32.TryParse(form["inspectionId"], out inspectionId);

                if (inspectionId != 0)
                {
                    IList<Models.Illustration> models = _dataManager.IllustrationModels.GetIllustrationsByInspectionId(inspectionId);
                    illustrations = (from m in models
                                     select new IllustrationInfo()
                                     {
                                         IllustrationId = m.IllustrationID,
                                         UserTitle = m.UserTitle,
                                         FileName = m.FileName,
                                         DivisionName = m.DivisionName,
                                         ThumbUrl = "/File/Thumb/" + m.FileName,
                                         ImageUrl = "/File/Illustration/" + m.FileName
                                     }).ToList();
                }
                else
                {
                    errorState = true;
                    errorMessage = "Обследование не найдено.";
                }
            }
            catch (Exception ex)
            {
                errorState = true;
                errorMessage = ex.Message;
            }

            return Json(
                new
                {
                    errorMessage = errorMessage,
                    errorState = errorState,
                    illustrations = illustrations
                }
            );
        }



        [HttpPost]
        public ActionResult AsyncDelete(int fileId)
        {
            bool errorState = false;    // default error state
            string errorMessage = String.Empty;

            try
            {
                Models.Illustration illustration = _dataManager.IllustrationModels.GetIllustrationById(fileId);

                if (illustration != null)
                {
                    // Удалить информацию о файле в базе
                    _dataManager.IllustrationModels.Remove(illustration);
                    _dataManager.Save();
                }
                else
                {
                    errorState = true;
                    errorMessage = "Иллюстрация не найдена.";
                }
            }
            catch (Exception ex)
            {
                errorState = true;
                errorMessage = ex.Message;
            }

            return Json(
                new
                {
                    errorMessage = errorMessage,
                    errorState = errorState
                }
            );
        }

        private string ValidateFileUpload(string fileName)
        {
            if (!FileManager.IsImage(fileName))
            {
                return "acceptFileTypes";
            }
            return String.Empty;
        }

    }
}

Navitas/Views/Shared/ConcurrencyError.cshtml
@{
    ViewBag.Title = "ConcurrencyError";
}

<h2>ConcurrencyError</h2>

<p>
Данные уже были отредактированны другим пользователем, либо удалены.
Попробуйте выполнить запрос еще раз.
</p>

Navitas/Views/Shared/IllustrationUploadForm.cshtml
@* Форма, изспользуемая для загрузки иллюстраций для здания.
*@   

@{
    int buildingId = (int)ViewData["BuildingId"];
    string sectionId = (string)ViewData["SectionId"];
    string dataJson = (string)ViewData["DataJson"];
}

   
@using (Html.BeginForm("AsyncUploadImage", "File", new { buildingId = buildingId, sectionId = sectionId }, FormMethod.Post, new { enctype = "multipart/form-data", @class = "ajaxuploadform" }))
{
    <input type="hidden" class="sectionid" value="@sectionId" />
    <input type="hidden" class="data" value="@dataJson" />
    <p>
        <label>Выберите файл для загрузки на сервер: <input class="inputFile" type="file" name="file" /></label>

        <a style="margin-left: 15px;" class="ajaxUploadButton" href="javascript:void(0)">Загрузить</a>
    </p>
            
    <div class="imagesContainer">
    </div>
}

Navitas/Views/Shared/IntakeTwelveMonths.cshtml
@model Navitas.ViewModels.Intake.TwelveMonthIntakeEditModel
    
@Html.HiddenFor(m=>m.BaseYear)

<table id="intakelastyear-container" class="singlerows">
    <thead>
        <tr>
            <th rowspan="2">@Navitas.Resources.Strings.OrderNumber</th>
            <th rowspan="2">@Navitas.Resources.Strings.EnergyResource</th>
            <th rowspan="2">@Navitas.Resources.Strings.MeasureUnit</th>
            <th colspan="12">@Navitas.Resources.Strings.Month</th>
            <th rowspan="2">@Navitas.Resources.Strings.ConsumptionTotal</th>
        </tr>
        <tr>
            <th>@Navitas.Resources.Strings.Month1Short</th>
            <th>@Navitas.Resources.Strings.Month2Short</th>
            <th>@Navitas.Resources.Strings.Month3Short</th>
            <th>@Navitas.Resources.Strings.Month4Short</th>
            <th>@Navitas.Resources.Strings.Month5Short</th>             
            <th>@Navitas.Resources.Strings.Month6Short</th>
            <th>@Navitas.Resources.Strings.Month7Short</th>
            <th>@Navitas.Resources.Strings.Month8Short</th>
            <th>@Navitas.Resources.Strings.Month9Short</th>
            <th>@Navitas.Resources.Strings.Month10Short</th>
            <th>@Navitas.Resources.Strings.Month11Short</th>
            <th>@Navitas.Resources.Strings.Month12Short</th>      
        </tr>
    </thead>
    <tbody>
        @for (int i = 0; i < Model.Values.Count; i++)
        {
            @* rowspan варьируется для разных пунктов и еще зависит от того, показываются ли строки с тарифами. *@
            int rowspan = Model.ShowTariffs ? 3 : 2;
            
            if (i == 1 && Model.ShowTariffs)
            {
                rowspan = 12;
            }
            else if (i == 1 && !Model.ShowTariffs)
            {
                rowspan = 8;
            }
            else if (i == 11 && Model.ShowTariffs)
            {
                rowspan = 14;
            }
            else if (i == 11 && !Model.ShowTariffs)
            {
                rowspan = 10;
            }
            
            @* Строка с объемами потребления *@
            <tr>
                @if (i != 2 && i != 3 && i != 4 && i != 12 && i != 13 && i != 14 && i != 15)
                {
                    <td rowspan="@rowspan.ToString()">@Html.Encode((i + 1).ToString())</td>
                }

                <td class="editor-label" @if (i == 11 || !Model.ShowTariffs) { <text>rowspan="2"</text> } else {<text>rowspan="3"</text>}>
                    @Html.Encode(Model.GetFieldTitle(i))
                </td>

                <td class="editor-label">@Html.Encode(Navitas.Resources.Strings.ConsumptionNatural + ", " + Model.ValueUnits[i])</td>
               
                @Html.EditorFor(model => model.Values[i], "TwelveMonthsNumbers", new { Prefix = "Values[" + i.ToString() + "]", ShowTotal = true })
            </tr>
                            
            @* Строка с затратами *@
            <tr>
                <td class="editor-label">@Navitas.Resources.Strings.InputsRublesNds</td>
                @Html.EditorFor(model => model.ValuesRUR[i], "TwelveMonthsNumbers", new { Prefix = "ValuesRUR[" + i.ToString() + "]", ShowTotal = true })
            </tr>
                
            @* Строка с тарифами *@
                if (Model.ShowTariffs)
                {
                <tr @if (i == 11)
                    { <text>style="display: none"</text> }>
                    <td class="editor-label">@Navitas.Resources.Strings.TariffRubles</td>
                    @Html.EditorFor(model => model.Tariffs[i], "TwelveMonthsNumbers", new { Prefix = "Tariffs[" + i.ToString() + "]", ShowTotal = false })
                </tr>
            }
        }
    </tbody>
</table>    
    

Navitas/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <title>@ViewBag.Title</title>

    @*<link href="@Url.Content("~/Content/themes/base/jquery-ui.css")" rel="stylesheet" type="text/css" />*@

    @if (HttpContext.Current.IsDebuggingEnabled)
    {
        <link href="@Url.Content("~/Content/05-jquery-ui.debug.css")" rel="stylesheet" type="text/css" />
        <link href="@Url.Content("~/Content/15-jquery.tooltip.debug.css")" rel="stylesheet" type="text/css" />
        <link href="@Url.Content("~/Content/20-jquery-ui-timepicker-addon.debug.css")" rel="stylesheet" type="text/css" />
        <link href="@Url.Content("~/Content/30-jHtmlArea.debug.css")" rel="stylesheet" type="text/css" />
        <link href="@Url.Content("~/Content/31-jHtmlArea.ColorPickerMenu.debug.css")" rel="stylesheet" type="text/css" />
        <link href="@Url.Content("~/Content/35-styles.debug.css")" rel="stylesheet" type="text/css" />
    }
    else
    {
       <link href="@Url.Content("~/Content/styles.bundle.css")" rel="stylesheet" type="text/css" />
    }

    <script src="@Url.Content("~/Scripts/jquery-1.8.2.js")" type="text/javascript"></script>
    <script src="@Url.Content("~/Scripts/jquery-ui-1.8.24.js")" type="text/javascript"></script>
    <script src="@Url.Content("~/Scripts/modernizr-2.6.2.js")" type="text/javascript"></script>
    <script src="@Url.Content("~/Scripts/jquery.tmpl.js")" type="text/javascript"></script>
    <script src="@Url.Content("~/Scripts/jquery.validate.js")" type="text/javascript"></script>
    <script src="@Url.Content("~/Scripts/jquery.validate.unobtrusive.js")" type="text/javascript"></script>

    @if (HttpContext.Current.IsDebuggingEnabled)
    {
        <script src="@Url.Content("~/Scripts/plugins/10-jquery-ui-timepicker-addon.debug.js")" type="text/javascript"></script>
        <script src="@Url.Content("~/Scripts/plugins/15-jquery.ui.datepicker-ru.debug.js")" type="text/javascript"></script>
        <script src="@Url.Content("~/Scripts/plugins/20-jquery-ui-timepicker-ru.debug.js")" type="text/javascript"></script>
        <script src="@Url.Content("~/Scripts/plugins/25-globalize.debug.js")" type="text/javascript"></script>
        <script src="@Url.Content("~/Scripts/plugins/30-jquery.tooltip.debug.js")" type="text/javascript"></script>
        <script src="@Url.Content("~/scripts/plugins/35-jquery.form.debug.js")" type="text/javascript"></script>
        <script src="@Url.Content("~/scripts/plugins/40-jquery.iframe-transport.debug.js")" type="text/javascript"></script>
        <script src="@Url.Content("~/scripts/plugins/45-jquery.fileupload.debug.js")" type="text/javascript"></script>
        <script src="@Url.Content("~/scripts/plugins/50-jquery.fileupload-ui.debug.js")" type="text/javascript"></script>
        <script src="@Url.Content("~/scripts/plugins/55-jquery.blockUI.debug.js")" type="text/javascript"></script>
        <script src="@Url.Content("~/scripts/plugins/60-jquery.jgrowl.debug.js")" type="text/javascript"></script>
        <script src="@Url.Content("~/Scripts/plugins/65-jHtmlArea-0.7.5.debug.js")" type="text/javascript"></script>
        <script src="@Url.Content("~/Scripts/plugins/66-jHtmlArea.ColorPickerMenu-0.7.0.debug.js")" type="text/javascript"></script>
    }
    else
    {
        <script src="@Url.Content("~/Scripts/plugins/plugins.bundle.js")" type="text/javascript"></script>
    }

    <script src="@Url.Content("~/Scripts/cultures/globalize.culture.ru-RU.js")" type="text/javascript"></script>

    <script type="text/javascript">
        var Navitas = {
            currentLanguage: "ru",
            resources: {
                // Сообщение об ошибке асинхронной загрузки
                ajaxErrorMessage: '@Navitas.Resources.Strings.InspectionStaff_ErrorAjaxRequest'
            }
        };

    </script>

    @if (HttpContext.Current.IsDebuggingEnabled)
    {
        <script src="@Url.Content("~/Scripts/navitas/03-utils.debug.js")" type="text/javascript"></script>
        <script src="@Url.Content("~/Scripts/navitas/05-jqvalidation.debug.js")" type="text/javascript"></script>
        <script src="@Url.Content("~/Scripts/navitas/08-autocalc.debug.js")" type="text/javascript"></script>
        <script src="@Url.Content("~/Scripts/navitas/10-inheritance.debug.js")" type="text/javascript"></script>
        <script src="@Url.Content("~/Scripts/navitas/20-ViewBase.debug.js")" type="text/javascript"></script>
        <script src="@Url.Content("~/Scripts/navitas/25-DynamicListView.debug.js")" type="text/javascript"></script>
    }
    else
    {
        <script src="@Url.Content("~/Scripts/navitas/navitas.bundle.js")" type="text/javascript"></script>
    }
</head>
<body>
    <div class="page">
        <header>
            <div id="title">
                <h1>Энергообследование от XXXIII.ru</h1>
            </div>
            <div id="logindisplay">
                @Html.Partial("_LogOnPartial")
            </div>
            <nav>
                <ul id="menu">
                    <li>@Html.ActionLink("Главная", "Index", "Home")</li>
                    <li>@Html.ActionLink("Обследования", "Index", "Inspection")</li>
                    <li>@Html.ActionLink("О ситеме", "About", "Home")</li>
                </ul>
            </nav>
        </header>
        <section id="main">
            @RenderBody()
        </section>
        <footer>
        </footer>
    </div>
</body>
</html>

Navitas/Views/Shared/_LogOnPartial.cshtml
@if(Request.IsAuthenticated) {
    <text>Здравствуйте, <strong>@User.Identity.Name</strong>!
    [ @Html.ActionLink("Выйти", "LogOff", "Account") ]</text>
}
else {
    @:[ @Html.ActionLink("Войти", "LogOn", "Account") ]
}

Navitas/Views/Shared/_ViewNavigation.cshtml
@model Navitas.Controls.ViewNavigationItems

@if ((Model & Navitas.Controls.ViewNavigationItems.Prev) == Navitas.Controls.ViewNavigationItems.Prev) {
    <input type="submit" name="buttonPrev" value="Назад" />
}

@if ((Model & Navitas.Controls.ViewNavigationItems.Save) == Navitas.Controls.ViewNavigationItems.Save) {
<input type="submit" name="buttonSave" value="Сохранить" />
}

@if ((Model & Navitas.Controls.ViewNavigationItems.Next) == Navitas.Controls.ViewNavigationItems.Next) {
<input type="submit" name="buttonNext" value="Далее" />
}